# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vd7EM8_A93VTXRVnaM-ARgQlrFdjF2V9
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title of the app
st.title("Gun Violence Patterns in New Mexico")

# File uploader for CSV
uploaded_file = st.file_uploader("Firearm Injury Death by Year, New Mexico and U.S.", type=["csv"])

if uploaded_file is not None:
    # Read the CSV file
    data = pd.read_csv(uploaded_file)
    st.write("### Data Preview")
    st.dataframe(data)

    # Dropdown for selecting columns
    columns = data.columns.tolist()
    x_column = st.selectbox("Select X-axis Column (Year)", columns)
    y_column = st.selectbox("Select Y-axis Column (Deaths per Year per 100,000)", columns)

    # Dropdown for graph type
    graph_type = st.selectbox(
        "Select Graph Type",
        ["Line", "Scatter", "Bar", "Pie"]
    )

    # Plot button
    if st.button("Plot Graph"):
        fig, ax = plt.subplots()

        try:
            if graph_type == "Line":
                ax.plot(data[x_column], data[y_column], marker='o')
                ax.set_title(f"{y_column} vs {x_column} (Line Plot)")

            elif graph_type == "Scatter":
                ax.scatter(data[x_column], data[y_column])
                ax.set_title(f"{y_column} vs {x_column} (Scatter Plot)")

            elif graph_type == "Bar":
                ax.bar(data[x_column], data[y_column])
                ax.set_title(f"{y_column} vs {x_column} (Bar Chart)")

            elif graph_type == "Pie":
                # Pie chart only makes sense for single-column data
                if len(data[x_column].unique()) <= 10:  # Limit to 10 unique categories for readability
                    plt.pie(
                        data[y_column],
                        labels=data[x_column],
                        autopct='%1.1f%%',
                        startangle=90,
                    )
                    plt.title(f"{y_column} (Pie Chart)")
                else:
                    st.error("Pie chart requires fewer unique categories in the X-axis.")
                    plt.close(fig)
                    return  # Exit to prevent further execution

            if graph_type != "Pie":
                ax.set_xlabel(x_column)
                ax.set_ylabel(y_column)
                st.pyplot(fig)
            else:
                st.pyplot(fig)

        except ValueError as e:
            st.error(f"Error: {e}")
        finally:
            plt.close(fig)

    st.write("Tip: Ensure the selected columns are numeric for meaningful plots.")
else:
    st.info("Please upload a CSV file to get started.")